config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'plans/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "plans#index"
  resources :plans do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '重要' },
    { id: 3, name: '任意' },
  ]

  include ActiveHash::Associations
  has_many :plans
  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :plan
  belongs_to :user

  validates :text, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_one_attached :image
  belongs_to :category
  has_many :comments
  has_many :reads, dependent: :destroy

  validates :title,       presence: true
  validates :text,        presence: true
  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plans
  has_many :comments
  has_many :reads, dependent: :destroy

  validates :name, presence: true 

  VALID_NAME_REGEX =/\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/ 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    Comment.create(comment_params)
    redirect_to root_path
  end

  def destroy
    Comment.find_by(id: params[:id],plan_id: params[:plan_id]).destroy
    redirect_to root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, plan_id: params[:plan_id])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_plan, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @plans = Plan.all
    @plans = Plan.includes(:user)
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    plan = Plan.find(params[:id])
    plan.destroy
    redirect_to root_path
  end

  def edit
    unless @plan.user_id == current_user.id
      :index
    end
  end

  def update
    plan = Plan.find(params[:id])
    plan.update(plan_params)
  end

  def show
    @comment = Comment.new
    @comments = @plan.comments.includes(:user)
    if Read.create(plan_id: @plan.id, user_id: current_user.id) 
      @read = Read.update(complete: true)
    end
  end

  private
  def plan_params
    params.require(:plan).permit(:title, :text, :category_id).merge(user_id: current_user.id)
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @plans = user.plans
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechoApp38290</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/plans/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @plan, local: true) do |form| %>
      <p>タイトル</p>
      <%= form.text_field :title, placeholder: "TITLE" %>
      <p>詳細</p>
      <%= form.text_area :text, placeholder: "TEXT", rows: "10" %>
      <p>カテゴリー</p>
      <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>
<div class='footer'>
  <%= link_to 'もどる', root_path %>
</div>

app/views/plans/index.html.erb
<h1> 予定掲示板 </h1>
<div class='header'>
  <% if user_signed_in? %> 
  <div class='left-content'> 
    こんにちは、<%= link_to current_user.name, "#", class: "user-name" %>さん
  </div>  
  <div class='right-content'>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
  </div>  
  <% else %>  
    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
  <% end %> 
</div>  
<div class='main'>
  <H2>投稿一覧</h2>
  <% @plans.each do |plan| %>
  <p>
  <div class='main-content'>
    ・<%= link_to plan.title, plan_path(plan.id) %>
  </div>  
  </p>
  <% end %>
</div>
<div class='footer-yotei'>
  <% if user_signed_in? %> 
    <%= link_to '新しい予定を投稿する', new_plan_path %>
  <% end %>
</div>

app/views/plans/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @plan, local: true) do |form| %>
    <%= render 'shared/error_messages', model: form.object %>
      <div class='field'>
        <p>タイトル</p>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>  
      <div class='field'>
        <p>内容</p>
        <%= form.text_area :text, placeholder: "内容", rows: "10" %>
      </div>  
      <div class='field'>
        <p>カテゴリー</p>
        <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
      </div>  
      <%= form.submit "送信" %>
    <% end %>
  </div>
</div>
<div class='footer'>
  <%= link_to 'もどる', root_path %>
</div>

app/views/plans/show.html.erb
<div class='header'>
  <div class='peji'>
  詳細ページ
  </div>
  <div class='syousai-hea'>
  <% if user = current_user.id == @plan.user_id %>
    <%= link_to '編集する', edit_plan_path(@plan.id) %>
    <%= link_to "削除する", plan_path(@plan.id), method: :delete %>
  <% end %>
  </div>
</div>  
<div class='main'>
  <%= @plan.title%>
    <p>★内容★</p>
  <%= @plan.text%>
  <div class="kidoku">
    <p><%= @read ? '既読' : '未読' %></p>
  </div>
  <p>☆コメント欄☆</p>
  <% if user_signed_in? %>
    <%= form_with(model: [@plan, @comment], local: true) do |form| %>
      <%= form.text_area :text, placeholder: "コメント", rows: "2" %>
      <%= form.submit "送信" %>
    <% end %>
  <% end %>
</div>  
<div class="comments">
  <h4>＜コメント一覧＞</h4>
  <% @comments.each do |comment| %>
      <%= link_to comment.user.name, "/users/#{comment.user_id}" %>
      <%= comment.text %>
      <% if current_user.id == @comment.user_id %>
      <p><%= link_to "削除する",  plan_comment_path(comment.plan.id, comment.id), method: :delete %></p>
      <% end %>
  <% end %>
</div>
<div class='footer'>
  <%= link_to 'もどる', root_path %>
</div>

app/views/plans/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>編集が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー情報</h1>
<div class="main">
  <%= @name %>さん
</div>
<div class="contents row">
  <p>投稿一覧</p>
  <% @plans.each do |plan| %>
    <p><%= link_to plan.title, plan_path(plan.id) %></p>
  <% end %>
</div>  
<div class='footer'>
  <%= link_to 'もどる', root_path %>
</div>